"use client";

import { FormEvent, useState } from "react";
import { protectImage, type PoisonResult } from "@/lib/poison-api";

export function ProtectionForm() {
  const [file, setFile] = useState<File>();
  const [intensity, setIntensity] = useState(0.35);
  const [result, setResult] = useState<PoisonResult>();
  const [error, setError] = useState<string>();
  const [isLoading, setIsLoading] = useState(false);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!file) return;
    setIsLoading(true);
    setError(undefined);
    try {
      setResult(await protectImage(file, intensity));
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Unexpected protection error");
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <form onSubmit={submit} className="rounded-3xl bg-white p-6 shadow-soft md:p-8">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <p className="text-sm font-semibold text-leaf">PROTECTION STUDIO</p>
          <h2 className="mt-1 text-2xl font-semibold">Prepare a protected preview</h2>
        </div>
        <span className="rounded-full bg-mint px-3 py-1 text-xs font-medium text-leaf">Private by default</span>
      </div>

      <label className="block rounded-2xl border-2 border-dashed border-emerald-200 bg-mint/30 p-8 text-center transition hover:border-leaf">
        <span className="block font-medium">Choose an artwork or product image</span>
        <span className="mt-1 block text-sm text-slate-500">PNG, JPG, or WebP · up to 15 MB</span>
        <input
          className="mt-4 block w-full text-sm"
          type="file"
          accept="image/png,image/jpeg,image/webp"
          onChange={(event) => setFile(event.target.files?.[0])}
        />
      </label>

      <label className="mt-6 block text-sm font-medium">
        Protection strength: {Math.round(intensity * 100)}%
        <input
          className="mt-3 w-full accent-emerald-700"
          type="range"
          min="0"
          max="1"
          step="0.05"
          value={intensity}
          onChange={(event) => setIntensity(Number(event.target.value))}
        />
        <span className="mt-1 block font-normal text-slate-500">Adds subtle changes intended to discourage automated reuse.</span>
      </label>

      <button
        className="mt-6 w-full rounded-xl bg-ink px-5 py-3 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50"
        disabled={!file || isLoading}
        type="submit"
      >
        {isLoading ? "Preparing protection…" : "Protect this image"}
      </button>

      {error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      {result && (
        <div className="mt-6 grid gap-4 rounded-2xl bg-sand p-4 sm:grid-cols-[120px_1fr]">
          {/* The source is generated by our service and intentionally rendered as a preview. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={result.poisoned_image_base64} alt="Protected preview" className="aspect-square w-full rounded-xl object-cover" />
          <div className="min-w-0 self-center">
            <p className="font-semibold text-leaf">Protected preview ready</p>
            <p className="mt-1 truncate text-xs text-slate-500" title={result.perturbation_hash}>Proof: {result.perturbation_hash}</p>
            <p className="mt-1 truncate text-xs text-slate-500" title={result.public_ipfs_cid}>Public reference: {result.public_ipfs_cid}</p>
          </div>
        </div>
      )}
    </form>
  );
}
