export const configSchemas = {
  web: {
    example: "apps/web/.env.example",
    keys: {
      NEXT_PUBLIC_POISON_ENGINE_URL: { type: "url", default: "http://localhost:8000" },
      AI_REVIEWER_URL: { type: "url", optional: true },
      NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: { type: "walletConnect", optional: true },
      NEXT_PUBLIC_CHAIN_ID: { type: "positiveInteger", default: "97" },
      NEXT_PUBLIC_BSC_RPC_URL: { type: "url", optional: true },
      NEXT_PUBLIC_TROVAYA_IP_NFT_ADDRESS: { type: "address", optional: true },
      NEXT_PUBLIC_TROVAYA_VAULT_ADDRESS: { type: "address", optional: true },
      NEXT_PUBLIC_IPFS_GATEWAY: { type: "url", default: "https://gateway.pinata.cloud/ipfs" },
      NEXT_PUBLIC_SUPABASE_URL: { type: "url", optional: true },
      NEXT_PUBLIC_SUPABASE_ANON_KEY: { type: "string", optional: true },
      SUPABASE_URL: { type: "url", optional: true },
      SUPABASE_ANON_KEY: { type: "string", optional: true },
      PINATA_JWT: { type: "string", optional: true },
      SUPABASE_SERVICE_ROLE_KEY: { type: "string", optional: true, secret: true },
      VAULT_RPC_URL: { type: "url", optional: true },
      VAULT_MASTER_KEY: { type: "base64Key32", optional: true, secret: true },
      DEMO_UPLOAD_TOKEN: { type: "string", optional: true, secret: true },
      NEXT_PUBLIC_DEMO_UPLOAD_TOKEN: { type: "string", optional: true },
    },
    groups: [
      ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY"],
      ["SUPABASE_URL", "SUPABASE_ANON_KEY"],
      ["SUPABASE_SERVICE_ROLE_KEY", "VAULT_RPC_URL", "VAULT_MASTER_KEY", "NEXT_PUBLIC_TROVAYA_IP_NFT_ADDRESS", "NEXT_PUBLIC_TROVAYA_VAULT_ADDRESS"],
      ["DEMO_UPLOAD_TOKEN", "NEXT_PUBLIC_DEMO_UPLOAD_TOKEN"],
    ],
  },
  indexer: {
    example: "services/event-indexer/.env.example",
    keys: {
      INDEXER_RPC_URL: { type: "url", requiredInRuntime: true },
      INDEXER_EXPECTED_CHAIN_ID: { type: "positiveInteger", default: "97" },
      TROVAYA_IP_NFT_ADDRESS: { type: "address", requiredInRuntime: true },
      INDEXER_START_BLOCK: { type: "nonNegativeInteger", default: "0" },
      DATABASE_URL: { type: "postgresUrl", requiredInRuntime: true, secret: true },
      INDEXER_CHUNK_SIZE: { type: "positiveInteger", default: "2000" },
      INDEXER_CONFIRMATIONS: { type: "nonNegativeInteger", default: "6" },
      INDEXER_REORG_DEPTH: { type: "positiveInteger", default: "12" },
      INDEXER_POLL_INTERVAL_MS: { type: "positiveInteger", default: "5000" },
      INDEXER_RETRY_ATTEMPTS: { type: "positiveInteger", default: "4" },
      INDEXER_RETRY_BASE_DELAY_MS: { type: "nonNegativeInteger", default: "500" },
      INDEXER_RETRY_MAX_DELAY_MS: { type: "nonNegativeInteger", default: "5000" },
    },
  },
  poison: {
    example: "services/poison-engine/.env.example",
    keys: {
      TROVAYA_ALLOWED_ORIGINS: { type: "urlList", default: "http://localhost:3000" },
      TROVAYA_PYTHON: { type: "string", optional: true },
      TROVAYA_UVICORN_HOST: { type: "host", default: "0.0.0.0" },
      TROVAYA_UVICORN_PORT: { type: "positiveInteger", default: "8000" },
      TROVAYA_UVICORN_WORKERS: { type: "positiveInteger", default: "1" },
    },
  },
  reviewer: {
    example: "services/ai-reviewer/.env.example",
    keys: {
      AI_REVIEWER_PROVIDER: { type: "string", default: "gemini" },
      GEMINI_API_KEY: { type: "string", optional: true, secret: true },
      GEMINI_MODEL: { type: "string", optional: true },
      AI_REVIEWER_GALLERY_RULES_PATH: { type: "string", optional: true },
      OLLAMA_URL: { type: "url", optional: true },
      OLLAMA_MODEL: { type: "string", optional: true },
      OLLAMA_TIMEOUT_SECONDS: { type: "positiveInteger", optional: true },
      CLOUD_LLM_URL: { type: "url", optional: true },
      CLOUD_LLM_API_KEY: { type: "string", optional: true, secret: true },
      CLOUD_LLM_MODEL: { type: "string", optional: true },
      AI_REVIEWER_TIMEOUT_SECONDS: { type: "positiveInteger", optional: true },
    },
  },
  contracts: {
    example: "packages/contracts/.env.example",
    keys: {
      DEPLOYER_PRIVATE_KEY: { type: "privateKey", optional: true, secret: true },
      LOCAL_CHAIN_RPC_URL: { type: "url", default: "http://127.0.0.1:8545" },
      BSC_TESTNET_RPC_URL: { type: "url", default: "https://data-seed-prebsc-1-s1.bnbchain.org:8545" },
      BASE_SEPOLIA_RPC_URL: { type: "url", default: "https://sepolia.base.org" },
      ARBITRUM_SEPOLIA_RPC_URL: { type: "url", default: "https://sepolia-rollup.arbitrum.io/rpc" },
      BSCSCAN_API_KEY: { type: "string", optional: true, secret: true },
      BASESCAN_API_KEY: { type: "string", optional: true, secret: true },
      ARBISCAN_API_KEY: { type: "string", optional: true, secret: true },
      ROLE_CHECK_RPC_URL: { type: "url", optional: true },
      TROVAYA_IP_NFT_ADDRESS: { type: "address", optional: true },
      TROVAYA_VAULT_ADDRESS: { type: "address", optional: true },
      EXPECTED_ADMIN_ADDRESS: { type: "address", optional: true },
      EXPECTED_PAUSER_ADDRESS: { type: "address", optional: true },
      EXPECTED_MINTER_ADDRESS: { type: "address", optional: true },
      DEPLOYER_ADDRESS: { type: "address", optional: true },
    },
  },
};
